### ISSUE TITLE
pander works only with development version from github

### ISSUE THREAD

**Issue by sebastiansauer** [sebastiansauer/Praxis_der_Datenanalyse#11]
works: devtools::install_github('Rapporter/pander')

CRAN does *not* work

**Comment by NMarkgraf** [comment]
Welche Fehlermeldung denn?

**Comment by sebastiansauer** [comment]
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent

Die erste Spalte kriegt keinen Namen oder so was in der Art....

cheerio
se




Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by sebastiansauer** [comment]
aber moment ich muss noch pushen :)


Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by sebastiansauer** [comment]
gepushed auf Master


Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by NMarkgraf** [comment]
Ich schau mal eben ...
Ich denke, dass da eine "deprecated"-Funktion benutzt wird. ... aber das ist nur ins blaue!

**Comment by sebastiansauer** [comment]
müsste bei jedem pander-Befehl der FAll sein.

Moment ich, glaube ich muss noch mal kurz aufräumen (noch mal pushen).


Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by NMarkgraf** [comment]
Habe ich mal per Workaround gefixet. - Wenn die pander im CRAN upgedatet haben können wir das wieder rausnehmen.

**Comment by sebastiansauer** [comment]
ah, pander ist noch nicht tibblebar. Danke!


Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by NMarkgraf** [comment]
Es ist noch schlimmer!

pander ist seit über einem Jahr tibblebar. - ABER der Autor hat noch keine Zeit gefunden die Development-Fassung in die CRAN-Fassung zu gießen. - Darum klappt es ja auch mit der ddv-version von pander ... traurig, traurig, traurig ...

Aber er hat versprochen, dass er sich mal darum kümmern wird ... :(

**Comment by sebastiansauer** [comment]
Gott stehe seiner armen Seele bei!


Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by NMarkgraf** [comment]
Ich bin ja bei ihm, wenn ich mal Zeit finde! ;-)
