### ISSUE TITLE
Cross-referencing in slides does not work

### ISSUE THREAD

**Issue by sebastiansauer** [sebastiansauer/Praxis_der_Datenanalyse#13]
Linking to some chapter header is not working. Eg., "see chapter 'Introduction'" will not link to Introduction. Instead all links refer back to title page.

This is not an issue of the customized latex-stylesheet. The issue appears with the basic beamer stylesheet.

**Comment by NMarkgraf** [comment]
Mir ist nicht ganz klar was Du nun meinst. - Beamer für die Slides, oder de PDF aus dem Buchprojekt?

**Comment by sebastiansauer** [comment]
Beamer für die Slides. Schau mal, hier hab ich es zusammen geschrieben.

<https://stackoverflow.com/questions/44520784/cross-referencing-not-working-in-rmarkdown-beamer-presentation> 

Mit \label und \ref ging es einigermaßen, aber nicht 100%.

**Comment by NMarkgraf** [comment]
Kein Wunder! - Dir fehlt ja "header_attributes" als Extension, wenn Du "normal" mit pandoc via RMarkdown übersetzt. ;-)

Guck mal hier: 
https://stackoverflow.com/questions/32492145/how-can-i-specify-pandocs-markdown-extensions-using-a-yaml-block

**Comment by NMarkgraf** [comment]
Wenn ich das richtig sehe, dann kann pandoc das beim übersetzen als BEAMER sowieso nicht! :-(
Schau dir mal die .md Dateien an und dann die .tex Dateien, einmal als Ziel Beamer und einmal als Ziel PDF... :(

**Comment by sebastiansauer** [comment]
Hm, die hyperlinks sind jedenfalls in beiden Varianten enhtalten? Die Extensions bringen bei mir jedenfalls nix: 

output: 
  pdf_document:
    keep_tex: yes
  beamer_presentation:
    md_extensions: +header_attributes+auto_identifiers
    keep_tex: yes

**Comment by NMarkgraf** [comment]
Nun ja, könnte daran liegen das es eben für LaTeX-PDF, nicht aber für LaTeX-Beamer implementiert ist. Ich schau mir das heute Abend noch mal genauer an.


---
Norman Markgraf : Guts-Muths-Weg 19 : 45136 Essen


Am 13.06.2017 um 17:22 schrieb Sebastian Sauer <notifications@github.com<mailto:notifications@github.com>>:


Hm, die hyperlinks sind jedenfalls in beiden Varianten enhtalten? Die Extensions bringen bei mir jedenfalls nix:

output:
pdf_document:
keep_tex: yes
beamer_presentation:
md_extensions: +header_attributes+auto_identifiers
keep_tex: yes

**Comment by sebastiansauer** [comment]
Dein Slides-Template läuft gut. Passt.
