### ISSUE TITLE
Pander tables do not support cross-referencing (apparently)

### ISSUE THREAD

**Issue by sebastiansauer** [sebastiansauer/Praxis_der_Datenanalyse#14]
Pander tables support line-break, as opposed to knitr::kable. However, they seem not to support cross-referencing (such as "see Table 3.2...").

**Comment by NMarkgraf** [comment]
Beispiel dazu bitte, wie willst Du es haben, wie ist es ... ;-)

Denke hier ist 'Nacharbeiten' von Nöten und ggf. ein paar Workarounds ...

**Comment by sebastiansauer** [comment]
Moin!

Schau mal den Screenshot an, da ist die Tabelle *nicht* referenziert:



Sie sollte es aber sein. Andere Tabellen sind referenziert (zB. Tab. 15.1).

Ich wollte mir mal das Markdown von pander anschauen, aber am schönsten wäre es, das an der Oberfläche lösen zu können.

Für Hinweise bin ich dankbar.

cheerio
se



Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by NMarkgraf** [comment]
https://github.com/Rapporter/pander/issues/258

**Comment by NMarkgraf** [comment]
https://stackoverflow.com/questions/41084793/referencing-a-simple-table-in-rmarkdown

**Comment by sebastiansauer** [comment]
Kann es sein, dass RStudio nicht meine gebrewte Version von pandoc zieht?

Aber wie kann ich ohne brew/cabal denn den crossref-Filter installieren? Any ideas??

cheerio
se


Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by sebastiansauer** [comment]
Bin wieder auf knitr::kable umgestiegen. 80%.

**Comment by NMarkgraf** [comment]
Nach Aussagen des Knitr-Programmieres sucht RStudio nach der aktuellsten pandoc-Version, die es (an den üblichen orten?) finden kann.

Also mal die Umgebungsvariablen checken!
