### ISSUE TITLE
slides_nm kompiliert nicht

### ISSUE THREAD

**Issue by sebastiansauer** [sebastiansauer/Praxis_der_Datenanalyse#15]
"slides_nm.Rmd" kompiliert nicht (bei mir). Fehlermeldung:

pandoc: Error running filter ./splitblockold.py
fd:5: hPutBuf: resource vanished (Broken pipe)
Error: pandoc document conversion failed with error 83

pinging @NMarkgraf

**Comment by NMarkgraf** [comment]
Du hast offenbar kein Python installiert. - Aber splitblockold.py ist auch nicht nötig (zur Zeit)!

**Comment by NMarkgraf** [comment]
https://stackoverflow.com/questions/36826916/pandoc-citeproc-error-83-with-rmarkdown-file

... Du hast da deine eigene pandoc genommen, oder?

**Comment by sebastiansauer** [comment]
doch:
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.


Aber, ja, es ging auch ohne...

Danke!

Sebastian


Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by luebby** [comment]
Hier: ! Undefined control sequence.
\setScreenRatio ...ight }{105mm} \par \ifstrequal 
                                                  {#1}{4x3}{\setlength {\myP...
l.40 \setScreenRatio{4x3}

.nm2 läuft

**Comment by NMarkgraf** [comment]
Müsste schon gefixed sein!
