### ISSUE TITLE
Fehlerhafte Links im gitbook!

### ISSUE THREAD

**Issue by NMarkgraf** [sebastiansauer/Praxis_der_Datenanalyse#19]
Irgendwie wurden fehlerhafte Links im GitBook erzeugt. Zum Beispiel:

https://sebastiansauer.github.io/Praxis_der_Datenanalyse/Rahmen.html

richtig wäre es, wenn alle Links nach dem letzten / nur noch in Minuskea da stehen würden. Also zum Beispiel:

https://sebastiansauer.github.io/Praxis_der_Datenanalyse/rahmen.html

Dies betrifft mindestens die  Abschnitten
Rahmen, Datenjudo!

Beste Grüße
Norman

**Comment by sebastiansauer** [comment]
Danke! Schau ich mir an. Ich vermute, es hängt mit den Section-IDs zusammen, die ich manuell erstellt habe.


Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by sebastiansauer** [comment]
fixed
